/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Core.Bot;
import Objetos.Ciudad;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADRIAN
 */
public class JPRecursos extends javax.swing.JPanel {

    /**
     * Creates new form JPRecursos
     */
    public JPRecursos() {
        initComponents();
        this.setBounds(0,0,600,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtaRecursos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jbtnActualizarRec = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtaRecursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ciudad", "Madera", "Vino", "Marmol", "Cristal", "Azufre"
            }
        ));
        jScrollPane1.setViewportView(jtaRecursos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 242));

        jLabel1.setFont(new java.awt.Font("Freestyle Script", 0, 36)); // NOI18N
        jLabel1.setText("Recursos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jbtnActualizarRec.setText("Actualizar");
        jbtnActualizarRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnActualizarRecActionPerformed(evt);
            }
        });
        add(jbtnActualizarRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnActualizarRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnActualizarRecActionPerformed
        DefaultTableModel modelo;
        ArrayList<Ciudad> misCiudades = new ArrayList();
        modelo = (DefaultTableModel) jtaRecursos.getModel();
        modelo.setRowCount(0);
        
        try { //Cargamos los datos de las ciudades le de BD
            misCiudades = Ciudad.ListCitiesPlayerBD();
            for (Ciudad ciudad : misCiudades) {
                modelo.addRow(new Object[]{(String) ciudad.getNombreCiu(), (int) ciudad.getMaderaCiu(), (int) ciudad.getVinoCiu(), (int) ciudad.getMarmolCiu(), (int) ciudad.getCristalCiu(), (int) ciudad.getAzufreCiu()}); //Lo agregamos a la caja
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(JPRecursos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnActualizarRecActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnActualizarRec;
    private javax.swing.JTable jtaRecursos;
    // End of variables declaration//GEN-END:variables
}
